name: Check and Lint confirm PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Initialize_workspace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install Dependencies
        run: npm install

      - name: Cache npm directory
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-


  Run_ESLint:
    runs-on: ubuntu-latest
    needs: [Initialize_workspace]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # HACK: Work-around for OoM error
      - name: Install Dependencies
        run: npm install

      - name: Lint with ESLint
        run: npm run ci:eslint

  Run_Stylelint:
    runs-on: ubuntu-latest
    needs: [Initialize_workspace]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Lint with Stylelint
        run: npm run ci:stylelint

  Run_Prettier:
    runs-on: ubuntu-latest
    needs: [Initialize_workspace]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-

      - name: Lint with Prettier
        run: npm run ci:prettier
